fitness_plus:
  metadata: "brand=fitness_plus"
  lut: "Cobi_3.CUBE"
  scroll_speed: 80
  watermarks:
    - "fitness_plus_watermark.png"
    - "fitness_plus_watermark_2.png"
    - "fitness_plus_watermark_3.png"
  captions_file: "fitness_plus_captions.txt"

athletic_elite:
  metadata: "brand=athletic_elite"
  lut: "Cobi_3.CUBE"
  scroll_speed: 120
  watermarks:
    - "gym_baddie_watermark.png"
    - "gym_baddie_watermark_2.png"
    - "gym_baddie_watermark_3.png"
  captions_file: "gym_baddie_captions.txt"

premium_fitness:
  metadata: "brand=premium_fitness"
  lut: null
  scroll_speed: 80
  watermarks:
    - "polished_watermark.png"
    - "polished_watermark_2.png"
    - "polished_watermark_3.png"
  captions_file: "polishedform_captions.txt"

travel_premium:
  metadata: "brand=travel_premium"
  lut: null
  scroll_speed: 80
  watermarks:
    - "asian_travel_watermark.png"
    - "asian_travel_watermark_2.png"
    - "asian_travel_watermark_3.png"
  captions_file: "asian_travel_captions.txt"
